### ISSUE TITLE
Doesn't work in Ember 2.0

### ISSUE THREAD

**Issue by sergetab** [BookingSync/ember-data-partial-model#15]
Tried to use it with Ember 2.0.2 and Ember Data 2.0.0, but it seems that it's not supported, it gives errors. Are there plans to support new versions? Thanks

**Comment by ZenCocoon** [comment]
Sorry to hear about this, we will look into this as clearly plan to have it work smooth with Ember 2.

**Comment by sergetab** [comment]
Great, looking forward to it. Thanks for the very useful addon.

**Comment by sergetab** [comment]
Any update on this?

**Comment by ZenCocoon** [comment]
@sergetab actually yes, we started looking at this today again and hope to have something ready in the next days.

**Comment by Azdaroth** [comment]
@sergetab We've just released 0.2.0 version with support for Ember 2.0.x and 2.1.x, you may want to try it out.
