### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by knownasilya** [BookingSync/ember-data-partial-model#17]
Could someone explain what the two arguments for `partial` do, e.g. `partial('user', 'extended'`?

Why redefine the property, i.e. `extended`?
Does the model name assume that you can load the extended data from another model?

**Comment by ZenCocoon** [comment]
Hey @knownasilya 

The two first attributes of the `partial` function are used to automatically create a relationship for the extended model, which includes additional data used to identify this relation as an extension of a partial model (setting `isPartialExtension: true`) as well as the extended attributes.
You can see the code for it at https://github.com/BookingSync/ember-data-partial-model/blob/master/addon/utils/model.js#L7 

The first params should be the partial `model` name and the second the extension name `extended`. We would like to remove this duplication but will need descriptors for this.

> Does the model name assume that you can load the extended data from another model?

No, this was not planned for it at least. If you like to load this extended attributes from a different endpoint from your server API, I would recommend updating your adapter and serializer instead.

If you like to look further about the extended model generation, have a look at:
https://github.com/BookingSync/ember-data-partial-model/blob/master/addon/mixins/store.js#L63

**Comment by knownasilya** [comment]
Thanks for clearing that up.

**Comment by ZenCocoon** [comment]
:+1: Glad to hear :)
