### ISSUE TITLE
Introduction to ember-data-partial-model at Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [BookingSync/ember-data-partial-model#19]
Hi there, would you someone familiar with the project would be open to giving an "Introduction to ember-partial-model" lightning talk at an upcoming Global Ember Meetup in the beginning of next year? We'll edit the video and give you video that you can embed into the addon's README. You can see an example of other introduction videos here https://vimeo.com/album/3607049

The talk usually covers:
1. What's use case for the addon?
2. How to get stated using it?
3. What should the user be aware of?

**Comment by Azdaroth** [comment]
Hi @taras, sounds good, I think it might be possible, when is next Global Ember Meetup going to happen?

**Comment by taras** [comment]
Hi @Azdaroth the next GEM is on January 16th at 12:00 New York time. Would this work for you?

**Comment by Azdaroth** [comment]
Sure, works for me :).

**Comment by taras** [comment]
I'm sorry, we seem to be booked for next 2 events. May I schedule you for Feb 27th?

**Comment by Azdaroth** [comment]
I'm afraid I won't be available then, how about March?

**Comment by taras** [comment]
March 19th?

**Comment by Azdaroth** [comment]
Sure, sounds good to me.

**Comment by taras** [comment]
Cool, you're on the list!

**Comment by Azdaroth** [comment]
:+1:
