### ISSUE TITLE
recommended way to register the pseudo-models manually?

### ISSUE THREAD

**Issue by kernel-io** [BookingSync/ember-data-partial-model#29]
Is there a recommended way to register the auto-generated models manually? (i.e: when I just want to .findRecord, instead of first loading the model into the store via a .query, then fetching the partial fields).
Currently I am just creating a model file and leaving it, I understand I can also trigger store.modelFor() but then I get the issue of where to place it...

this is what I'm doing below

```javascript
import DS from 'ember-data'

const {
  Model
} = DS

const hackyModel =  Model.extend()

hackyModel.reopenClass({
  _extendPartialModel: 'transaction'
})

export default hackyModel

```

**Comment by Azdaroth** [comment]
Hi @kernel-io ,

Currently, there is no recommended way to do so, you might check this code: https://github.com/BookingSync/ember-data-partial-model/blob/master/addon/mixins/store.js#L7-L13 , but that would mean coupling to private methods, so not sure if this is the best idea. I think your current solution is the most reasonable way to handle it for now.

**Comment by kernel-io** [comment]
cool thanks @Azdaroth
