### ISSUE TITLE
Override Model.save() to loadPartials() before saving

### ISSUE THREAD

**Issue by ZenCocoon** [BookingSync/ember-data-partial-model#8]
Right now this is needed:

```
user.loadPartials()
  .then(user => user.save())
  .catch(error => {
    ...
  });
```

**Comment by igorT** [comment]
Should be configurable

**Comment by ZenCocoon** [comment]
The current version is made for APIs that do NOT support partial updates, which should not harm other ones but make useless requests. Moving forward we want to have a configuration to support both types.

**Comment by Azdaroth** [comment]
I guess this can be closed, right? We already have it done: https://github.com/BookingSync/ember-data-partial-model/blob/master/addon/utils/model.js#L32
